<?php

$traducciones = [
    'es' => [
        // General
        'app_nombre'            => 'TicKeep',
        'salir'                 => 'Salir',
        'volver'                => '← Volver a mis garantías',
        'guardar'               => 'Guardar configuración',
        'editar'                => 'Editar',
        'borrar'                => 'Borrar',
        'cerrar_sesion'         => 'Cerrar sesión',
        'footer'                => '© 2025 TicKeep. Todos los derechos reservados.',
        'footer_sub'            => 'Tu tranquilidad, garantizada.',

        // Index
        'mis_garantias'         => 'Mis garantías',
        'garantia_registrada'   => 'garantía registrada',
        'garantias_registradas' => 'garantías registradas',
        'exportar'              => 'Exportar',
        'exportar_pdf'          => 'Exportar a PDF',
        'exportar_excel'        => 'Exportar a Excel',
        'nueva_garantia'        => '+ Nueva garantía',
        'lista'                 => 'Lista',
        'calendario'            => 'Calendario',
        'buscar'                => 'Buscar por producto o tienda...',
        'filtro_todo'           => 'Todo',
        'filtro_vigente'        => 'Vigente',
        'filtro_expira'         => 'Próximo a vencer',
        'filtro_caducada'       => 'Caducada',
        'comprado_en'           => 'Comprado en:',
        'vence_el'              => 'Vence el:',
        'quedan'                => 'Quedan',
        'dias'                  => 'días',
        'vence_hoy'             => 'Vence hoy',
        'caduco_hace'           => 'Caducó hace',
        'ver_detalles'          => 'Ver detalles',
        'sin_garantias'         => 'No tienes garantías registradas aún.',
        'anadir_primera'        => '+ Añadir primera garantía',
        'sin_resultados'        => 'No se encontraron garantías con ese criterio.',
        'vigente'               => 'Vigente',
        'expira_pronto'         => 'Expira pronto',
        'caducada'              => 'Caducada',

        // Detalle
        'titulo_detalle'        => 'Ver artículo - TicKeep',
        'tienda'                => 'Tienda:',
        'no_indicada'           => 'No indicada',
        'fecha_compra'          => 'Fecha de compra:',
        'fin_garantia'          => 'Fin de garantía:',
        'comentarios'           => 'Comentarios personales',
        'comentarios_desc'      => 'Comentarios privados para recordar información relevante sobre esta garantía.',
        'sin_comentarios'       => 'Todavía no hay comentarios guardados.',
        'nuevo_comentario'      => 'Escribe un nuevo comentario...',
        'añadir_comentario'     => 'Añadir comentario',
        'comentario_vacio'      => 'Escribe un comentario antes de añadirlo.',
        'comentario_ok'         => 'Comentario añadido correctamente.',

        // Nueva garantía
        'titulo_nueva'          => 'Nueva garantía - TicKeep',
        'nueva_titulo'          => 'Añadir una nueva garantía',
        'nombre_producto'       => 'Nombre del producto',
        'fecha_vencimiento'     => 'Fecha de vencimiento',
        'subir_ticket'          => 'Subir ticket',
        'escanear_ticket'       => 'Escanear ticket',
        'foto_producto'         => 'Seleccionar foto del producto',
        'ticket_actual'         => 'Ticket actual:',
        'foto_actual'           => 'Foto actual:',
        'anadir_producto'       => 'Añadir producto',
        'error_campos'          => 'Por favor, rellena nombre del producto, fecha de compra y fecha de vencimiento.',
        'error_fecha'           => 'La fecha de vencimiento no puede ser anterior a la fecha de compra.',

        // Editar garantía
        'titulo_editar'         => 'Editar garantía - TicKeep',
        'editar_titulo'         => 'Editar garantía',
        'guardar_cambios'       => 'Guardar cambios',
        'confirmar_borrar'      => '¿Seguro que quieres borrar esta garantía?',

        // Configuración
        'titulo_config'         => 'Configuración - TicKeep',
        'config_titulo'         => 'Configuración',
        'config_subtitulo'      => 'Personaliza tu cuenta y el comportamiento de TicKeep con opciones útiles y prácticas.',
        'perfil'                => 'Perfil',
        'seguridad'             => 'Seguridad',
        'notificaciones'        => 'Notificaciones',
        'apariencia'            => 'Apariencia',
        'gestion'               => 'Gestión de garantías',
        'nombre_usuario'        => 'Nombre de usuario',
        'nombre_help'           => 'Nombre visible dentro de la aplicación.',
        'correo'                => 'Correo electrónico',
        'correo_help'           => 'Correo usado para avisos y acceso a la cuenta.',
        'pass_actual'           => 'Contraseña actual',
        'pass_nueva'            => 'Nueva contraseña',
        'pass_confirmar'        => 'Confirmar nueva contraseña',
        'pass_nota'             => 'Si quieres cambiar la contraseña, escribe primero la actual. Si no, deja estos campos vacíos.',
        'notif_email'           => 'Notificaciones por correo',
        'notif_email_help'      => 'Activa o desactiva el envío de emails desde la aplicación.',
        'notif_app'             => 'Notificaciones dentro de la app',
        'notif_app_help'        => 'Preparado para mostrar avisos internos en el panel principal.',
        'aviso_venc'            => 'Avisar cuando una garantía vaya a expirar pronto',
        'aviso_venc_help'       => 'Te permite definir con cuánta antelación quieres recibir el aviso.',
        'antelacion'            => 'Antelación del aviso',
        'frecuencia'            => 'Frecuencia del recordatorio',
        'hora_aviso'            => 'Hora preferida del aviso',
        'solo_una_vez'          => 'Solo una vez',
        'semanal'               => 'Semanal',
        'diario'                => 'Diario',
        'notif_caducadas'       => 'Avisar también cuando una garantía ya haya caducado',
        'notif_caducadas_help'  => 'Útil para tener control de las garantías que ya vencieron.',
        'resumen_mensual'       => 'Recibir resumen mensual',
        'resumen_mensual_help'  => 'Resumen con garantías vigentes, próximas a vencer y caducadas.',
        'idioma'                => 'Idioma',
        'tema'                  => 'Tema',
        'tema_claro'            => 'Claro',
        'tema_oscuro'           => 'Oscuro',
        'tema_sistema'          => 'Según el sistema',
        'formato_fecha'         => 'Formato de fecha',
        'color_principal'       => 'Color principal',
        'ordenar_por'           => 'Ordenar garantías por',
        'mostrar_dias'          => 'Mostrar días restantes hasta el vencimiento',
        'mostrar_dias_help'     => 'Muy útil para ver rápidamente cuánto tiempo le queda a cada garantía.',
        'confirmar_elim'        => 'Pedir confirmación al borrar una garantía',
        'confirmar_elim_help'   => 'Recomendado para evitar borrar garantías por error.',
        'orden_compra_desc'     => 'Fecha de compra (más reciente primero)',
        'orden_compra_asc'      => 'Fecha de compra (más antigua primero)',
        'orden_venc_asc'        => 'Fecha de vencimiento (más próxima primero)',
        'orden_venc_desc'       => 'Fecha de vencimiento (más lejana primero)',
        'orden_nombre_asc'      => 'Nombre (A-Z)',
        'orden_nombre_desc'     => 'Nombre (Z-A)',
        'config_guardada'       => 'Configuración guardada correctamente.',
        'config_error'          => 'Error al guardar la configuración.',
        'campo_obligatorio'     => 'El nombre y el correo son obligatorios.',
        'email_invalido'        => 'El correo electrónico no tiene un formato válido.',
        'pass_no_coincide'      => 'La nueva contraseña y su confirmación no coinciden.',
        'pass_corta'            => 'La nueva contraseña debe tener al menos 6 caracteres.',
        'pass_actual_mal'       => 'La contraseña actual no es correcta.',
        'email_en_uso'          => 'Ese correo electrónico ya está siendo usado por otro usuario.',
    ],

    'en' => [
        // General
        'app_nombre'            => 'TicKeep',
        'salir'                 => 'Logout',
        'volver'                => '← Back to my warranties',
        'guardar'               => 'Save settings',
        'editar'                => 'Edit',
        'borrar'                => 'Delete',
        'cerrar_sesion'         => 'Sign out',
        'footer'                => '© 2025 TicKeep. All rights reserved.',
        'footer_sub'            => 'Your peace of mind, guaranteed.',

        // Index
        'mis_garantias'         => 'My warranties',
        'garantia_registrada'   => 'warranty registered',
        'garantias_registradas' => 'warranties registered',
        'exportar'              => 'Export',
        'exportar_pdf'          => 'Export to PDF',
        'exportar_excel'        => 'Export to Excel',
        'nueva_garantia'        => '+ New warranty',
        'lista'                 => 'List',
        'calendario'            => 'Calendar',
        'buscar'                => 'Search by product or store...',
        'filtro_todo'           => 'All',
        'filtro_vigente'        => 'Active',
        'filtro_expira'         => 'Expiring soon',
        'filtro_caducada'       => 'Expired',
        'comprado_en'           => 'Purchased at:',
        'vence_el'              => 'Expires on:',
        'quedan'                => 'Left:',
        'dias'                  => 'days',
        'vence_hoy'             => 'Expires today',
        'caduco_hace'           => 'Expired',
        'ver_detalles'          => 'View details',
        'sin_garantias'         => 'You have no registered warranties yet.',
        'anadir_primera'        => '+ Add first warranty',
        'sin_resultados'        => 'No warranties found for that criteria.',
        'vigente'               => 'Active',
        'expira_pronto'         => 'Expiring soon',
        'caducada'              => 'Expired',

        // Detalle
        'titulo_detalle'        => 'View item - TicKeep',
        'tienda'                => 'Store:',
        'no_indicada'           => 'Not specified',
        'fecha_compra'          => 'Purchase date:',
        'fin_garantia'          => 'Warranty end:',
        'comentarios'           => 'Personal notes',
        'comentarios_desc'      => 'Private notes to remember relevant information about this warranty.',
        'sin_comentarios'       => 'No notes saved yet.',
        'nuevo_comentario'      => 'Write a new note...',
        'añadir_comentario'     => 'Add note',
        'comentario_vacio'      => 'Write a note before adding it.',
        'comentario_ok'         => 'Note added successfully.',

        // Nueva garantía
        'titulo_nueva'          => 'New warranty - TicKeep',
        'nueva_titulo'          => 'Add a new warranty',
        'nombre_producto'       => 'Product name',
        'fecha_vencimiento'     => 'Expiry date',
        'subir_ticket'          => 'Upload receipt',
        'escanear_ticket'       => 'Scan receipt',
        'foto_producto'         => 'Select product photo',
        'ticket_actual'         => 'Current receipt:',
        'foto_actual'           => 'Current photo:',
        'anadir_producto'       => 'Add product',
        'error_campos'          => 'Please fill in product name, purchase date and expiry date.',
        'error_fecha'           => 'The expiry date cannot be before the purchase date.',

        // Editar garantía
        'titulo_editar'         => 'Edit warranty - TicKeep',
        'editar_titulo'         => 'Edit warranty',
        'guardar_cambios'       => 'Save changes',
        'confirmar_borrar'      => 'Are you sure you want to delete this warranty?',

        // Configuración
        'titulo_config'         => 'Settings - TicKeep',
        'config_titulo'         => 'Settings',
        'config_subtitulo'      => 'Customize your account and TicKeep behavior with useful and practical options.',
        'perfil'                => 'Profile',
        'seguridad'             => 'Security',
        'notificaciones'        => 'Notifications',
        'apariencia'            => 'Appearance',
        'gestion'               => 'Warranty management',
        'nombre_usuario'        => 'Username',
        'nombre_help'           => 'Name visible within the application.',
        'correo'                => 'Email address',
        'correo_help'           => 'Email used for notifications and account access.',
        'pass_actual'           => 'Current password',
        'pass_nueva'            => 'New password',
        'pass_confirmar'        => 'Confirm new password',
        'pass_nota'             => 'To change your password, enter your current one first. Otherwise, leave these fields empty.',
        'notif_email'           => 'Email notifications',
        'notif_email_help'      => 'Enable or disable email sending from the application.',
        'notif_app'             => 'In-app notifications',
        'notif_app_help'        => 'Ready to show internal alerts in the main panel.',
        'aviso_venc'            => 'Notify when a warranty is about to expire',
        'aviso_venc_help'       => 'Set how far in advance you want to receive the alert.',
        'antelacion'            => 'Notice period',
        'frecuencia'            => 'Reminder frequency',
        'hora_aviso'            => 'Preferred alert time',
        'solo_una_vez'          => 'Only once',
        'semanal'               => 'Weekly',
        'diario'                => 'Daily',
        'notif_caducadas'       => 'Also notify when a warranty has already expired',
        'notif_caducadas_help'  => 'Useful to keep track of expired warranties.',
        'resumen_mensual'       => 'Receive monthly summary',
        'resumen_mensual_help'  => 'Summary with active, expiring soon and expired warranties.',
        'idioma'                => 'Language',
        'tema'                  => 'Theme',
        'tema_claro'            => 'Light',
        'tema_oscuro'           => 'Dark',
        'tema_sistema'          => 'System default',
        'formato_fecha'         => 'Date format',
        'color_principal'       => 'Main color',
        'ordenar_por'           => 'Sort warranties by',
        'mostrar_dias'          => 'Show days remaining until expiry',
        'mostrar_dias_help'     => 'Very useful to quickly see how much time each warranty has left.',
        'confirmar_elim'        => 'Ask for confirmation before deleting a warranty',
        'confirmar_elim_help'   => 'Recommended to avoid deleting warranties by mistake.',
        'orden_compra_desc'     => 'Purchase date (newest first)',
        'orden_compra_asc'      => 'Purchase date (oldest first)',
        'orden_venc_asc'        => 'Expiry date (soonest first)',
        'orden_venc_desc'       => 'Expiry date (latest first)',
        'orden_nombre_asc'      => 'Name (A-Z)',
        'orden_nombre_desc'     => 'Name (Z-A)',
        'config_guardada'       => 'Settings saved successfully.',
        'config_error'          => 'Error saving settings.',
        'campo_obligatorio'     => 'Name and email are required.',
        'email_invalido'        => 'The email address is not valid.',
        'pass_no_coincide'      => 'The new password and confirmation do not match.',
        'pass_corta'            => 'The new password must be at least 6 characters.',
        'pass_actual_mal'       => 'The current password is incorrect.',
        'email_en_uso'          => 'That email address is already being used by another user.',
    ],
];

// Determinar idioma activo
$idiomaActivo = 'es';
if (isset($preferencias['idioma']) && $preferencias['idioma'] === 'Inglés') {
    $idiomaActivo = 'en';
}

// $t es el array de traducciones activo
$t = $traducciones[$idiomaActivo];
